name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  PNPM_VERSION: 10.x
  CACHE_KEY_PREFIX: v2

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install deps (offline if cached)
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Biome
        run: pnpm lint:biome

      - name: Run ESLint
        run: pnpm lint:eslint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install deps (offline if cached)
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-playwright-${{ hashFiles('playwright.config.*') }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-playwright-

      - name: Ensure Chromium is present
        run: npx playwright install chromium

      - name: Run Vitest
        run: pnpm test